codecov:
  branch: develop
coverage:
  range: 70...100
  status:
    project:
      default:
        target: auto
        paths: "!test/"
      syntax:
        target: auto
        paths: "libsolidity/analysis"
        flags: syntax
      tests:
        target: auto
        paths: "test/"
comment:
  layout: "reach, diff, flags"
